### ISSUE TITLE
TF2 Server Initialization bug (un-connect-able if default settings is used)

### ISSUE THREAD

**Issue by le-lel190** [BattlefieldDuck/WindowsGSM#127]
The bug is as title, the server will simply not allow anyone to connect if the default settings provided by WindowsGSM is used.

However if i dont specify a local IP (by removing the default IP in windowsGSM, and then input a "+ip" launch argument without parameters in "Server start para" and also remove the "+clientport" thing, 
![image](https://user-images.githubusercontent.com/89120313/177173463-33e982c1-77e4-4d88-9277-0293854362fb.png)

it will start to work as intended again

**Comment by GeekbeeGER** [comment]
+clientport is not Serverparameter! correct is -Port! stop watch old videos....

**Comment by lel190-alt** [comment]
yes however the "+clientport" is literally a default settings if you create a TF2 server via WindowsGSM

**Comment by GeekbeeGER** [comment]
[It's for multiple PCs connecting to Steam servers behind the same router; it configures their client port to a different one than default so communications don't interfere with eachother.](https://help.steampowered.com/en/faqs/view/48C1-A297-4839-8BB8)

**Comment by lel190-alt** [comment]
Alright thanks for the info then 🤔
