### ISSUE TITLE
_restart command stops the server instead of restarting

### ISSUE THREAD

**Issue by IntensityGit** [BattlefieldDuck/WindowsGSM#4]
**Describe the bug**
When I restart my csgo servers I use the _restart command but WindowsGSM recognizes this as a stop command and doesn't restart the server.

**To Reproduce**
Go to the console type _restart.

**Expected behavior**
The server to close and restart but instead it's recognized as a stop command and just shuts down.

**Comment by BattlefieldDuck** [comment]
Thanks for the report!

**The cause of the problem**
As both `quit` and `_restart` commands return exitcode `0` which means WindowsGSM thinks the server stopped successfully, so the server will not auto-restart.

**In the next patch**
WindowsGSM will "ignore" the exitcode, any reasons cause the server stopped externally will be seen as server crashed. That's mean if `autorestart="1"` and, the server will auto-restart in your case.

**Comment by IntensityGit** [comment]
Perfect, thank you.
